module.exports = {
  FUENTE: ['Calco reducido', 'Fotografía', 'Dibujo', 'Reconstrucción de laboratorio'],
  CLASE: ['Zoomorfos', 'Geométricos', 'Escenas', 'Objetos', 'Cubiertas', 'Combinada'],
  GRUPO: ['Antropomorfos', 'Animalomorfos', 'Zooantropomorfos', 'Elementos', 'Figuras', 'Otro (ver Cuadro N° 7)'],
  UBICACION: [
    'Arriba-izquierda',
    'Arriba-centro',
    'Arriba-derecha',
    'Centro-izquierda',
    'Centro-centro',
    'Centro-derecha',
    'Abajo-izquierda',
    'Abajo-centro',
    'Abajo-derecha',
  ],
  MANTENIMIENTO: ['Ninguno', 'Repintado', 'Regrabado'],

  TIPO_TECNICA: ['grabado', 'pintura', 'mixta'],
  GRABADO_CARACTERISTICA: ['Homogéneo', 'Heterogéneo'],
  GRABADO_TIPO: ['Picado', 'Raspado', 'Incisión', 'Horadación'],
  GRABADO_TOPOGRAFIA: ['Lineal', 'Perimetral', 'Areal-Superficial'],
  GRABADO_ANCHO_TRAZO: ['Fino', 'Grueso'],
  GRABADO_ESPESOR: ['Superficial', 'Profundo'],
  GRABADO_FORMA_SURCO: ['U', 'V'],

  PINTURA_CARACTERISTICA: ['Plana', 'Lineal', 'Punteado', 'Combinada'],
  PINTURA_COMBINACION: ['Plano y lineal', 'Plano y punteado', 'Lineal y punteado', 'Plano-lineal-punteado'],

  MIXTA_ORDEN: [
    'Grabado sobre pintado',
    'Pintura sobre grabado',
    'Grabado sobre grabado',
    'Grabado y pintado',
  ],

  GENERO: ['Masculino', 'Femenino', 'Indeterminado'],
  NORMA: ['Frontal', 'Lateral', 'No determinada'],
  REPRESENTACION: ['Parcial', 'Completa'],
  TRATAMIENTO_CABEZA: ['Naturalista', 'Esquemático', 'Geométrico', 'Embozado', 'Fantástico'],
  TRATAMIENTO_CUERPO: ['Naturalista', 'Esquemático', 'Geométrico', 'Encubierto', 'Fantástico'],
  TRATAMIENTO_EXTREMIDADES: ['Naturalista', 'Esquemático', 'Geométrico', 'Fantástico', 'En tridígito'],
  VESTIDO: ['Ausente', 'Coraza', 'Cubierta indeterminada', 'Quillango'],
  ADORNOS: [
    'Ausente',
    'Aros',
    'Hacha',
    'Koorto',
    'Orejeras',
    'Orejeras-boleadora',
    'Orejeras-pintura facial-boleadora',
    'Tembentá-pectoral-cinturón-boleadora',
    'Tocado cefálico-hacha Elumgássūm',
    'Tocado cefálico',
  ],
  ORGANOS_SEXUALES_TRATAMIENTO: ['Naturalista', 'Esquemático', 'Fantástico'],
};
